// Generated by tmpl
// https://github.com/benbjohnson/tmpl
//
// DO NOT EDIT!
// Source: column_writer.gen.go.tmpl

// Copyright 2020 The Meerkat Authors
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package storage

import (
	"meerkat/internal/storage/encoding"
	"meerkat/internal/storage/index"
	"meerkat/internal/storage/io"
)

func NewInt64ColumnWriter(columnType ColumnType,
	src Int64ColumnSource,
	encoder encoding.Int64Encoder,
	colIndex index.Int64IndexWriter,
	blockIndex index.BlockIndexWriter,
	validityIndex index.ValidityIndexWriter,
	bw *io.BinaryWriter) *Int64ColumnWriter {

	return &Int64ColumnWriter{
		columnType: columnType,
		src:        src,
		bw:         bw,
		encoder:    encoder,
		colIndex:   colIndex,
		blockIndex: blockIndex,
		validity:   validityIndex,
	}

}

type Int64ColumnWriter struct {
	columnType  ColumnType
	bw          *io.BinaryWriter
	src         Int64ColumnSource
	encoder     encoding.Int64Encoder
	colIndex    index.Int64IndexWriter
	blockIndex  index.BlockIndexWriter
	validity    index.ValidityIndexWriter
	numOfValues int
	cardinality int

	blkEnd         int
	blkIdxEnd      int
	encoderEnd     int
	colIdxEnd      int
	validityIdxEnd int
}

func (w *Int64ColumnWriter) Write() {

	for w.src.HasNext() {

		values := w.src.Next()

		w.numOfValues += values.Len()

		w.encoder.Encode(values)

		if w.colIndex != nil {
			w.colIndex.Index(values)
		}

		if w.src.HasNulls() {
			w.validity.Index(values.Rid())
		}

	}

	w.encoder.FlushBlocks()

	w.blkEnd = w.bw.Offset()

	// some column types like boolean col don't write blocks.
	if w.blockIndex != nil {

		w.blockIndex.Flush()

		w.blkIdxEnd = w.bw.Offset()

	}

	w.encoder.Flush()

	w.encoderEnd = w.bw.Offset()

	// TODO(gvelo) if the column is not indexed estimate
	// cardinality anyways using datasketches.
	if w.colIndex != nil {

		w.colIndex.Flush()

		w.colIdxEnd = w.bw.Offset()

		w.cardinality = w.colIndex.Cardinality()

	}

	if w.src.HasNulls() {

		w.validity.Flush()

		w.validityIdxEnd = w.bw.Offset()

	}

	w.writeFooter()

}

func (w *Int64ColumnWriter) writeFooter() {

	entry := w.bw.Offset()

	w.bw.WriteUvarint(int(w.encoder.Type()))
	w.bw.WriteUvarint(w.blkEnd)
	w.bw.WriteUvarint(w.blkIdxEnd)
	w.bw.WriteUvarint(w.encoderEnd)
	w.bw.WriteUvarint(w.colIdxEnd)
	w.bw.WriteUvarint(w.validityIdxEnd)
	w.bw.WriteUvarint(w.numOfValues)
	w.bw.WriteUvarint(w.cardinality)

	w.bw.WriteFixedInt(entry)

}

func NewInt32ColumnWriter(columnType ColumnType,
	src Int32ColumnSource,
	encoder encoding.Int32Encoder,
	colIndex index.Int32IndexWriter,
	blockIndex index.BlockIndexWriter,
	validityIndex index.ValidityIndexWriter,
	bw *io.BinaryWriter) *Int32ColumnWriter {

	return &Int32ColumnWriter{
		columnType: columnType,
		src:        src,
		bw:         bw,
		encoder:    encoder,
		colIndex:   colIndex,
		blockIndex: blockIndex,
		validity:   validityIndex,
	}

}

type Int32ColumnWriter struct {
	columnType  ColumnType
	bw          *io.BinaryWriter
	src         Int32ColumnSource
	encoder     encoding.Int32Encoder
	colIndex    index.Int32IndexWriter
	blockIndex  index.BlockIndexWriter
	validity    index.ValidityIndexWriter
	numOfValues int
	cardinality int

	blkEnd         int
	blkIdxEnd      int
	encoderEnd     int
	colIdxEnd      int
	validityIdxEnd int
}

func (w *Int32ColumnWriter) Write() {

	for w.src.HasNext() {

		values := w.src.Next()

		w.numOfValues += values.Len()

		w.encoder.Encode(values)

		if w.colIndex != nil {
			w.colIndex.Index(values)
		}

		if w.src.HasNulls() {
			w.validity.Index(values.Rid())
		}

	}

	w.encoder.FlushBlocks()

	w.blkEnd = w.bw.Offset()

	// some column types like boolean col don't write blocks.
	if w.blockIndex != nil {

		w.blockIndex.Flush()

		w.blkIdxEnd = w.bw.Offset()

	}

	w.encoder.Flush()

	w.encoderEnd = w.bw.Offset()

	// TODO(gvelo) if the column is not indexed estimate
	// cardinality anyways using datasketches.
	if w.colIndex != nil {

		w.colIndex.Flush()

		w.colIdxEnd = w.bw.Offset()

		w.cardinality = w.colIndex.Cardinality()

	}

	if w.src.HasNulls() {

		w.validity.Flush()

		w.validityIdxEnd = w.bw.Offset()

	}

	w.writeFooter()

}

func (w *Int32ColumnWriter) writeFooter() {

	entry := w.bw.Offset()

	w.bw.WriteUvarint(int(w.encoder.Type()))
	w.bw.WriteUvarint(w.blkEnd)
	w.bw.WriteUvarint(w.blkIdxEnd)
	w.bw.WriteUvarint(w.encoderEnd)
	w.bw.WriteUvarint(w.colIdxEnd)
	w.bw.WriteUvarint(w.validityIdxEnd)
	w.bw.WriteUvarint(w.numOfValues)
	w.bw.WriteUvarint(w.cardinality)

	w.bw.WriteFixedInt(entry)

}

func NewFloat64ColumnWriter(columnType ColumnType,
	src Float64ColumnSource,
	encoder encoding.Float64Encoder,
	colIndex index.Float64IndexWriter,
	blockIndex index.BlockIndexWriter,
	validityIndex index.ValidityIndexWriter,
	bw *io.BinaryWriter) *Float64ColumnWriter {

	return &Float64ColumnWriter{
		columnType: columnType,
		src:        src,
		bw:         bw,
		encoder:    encoder,
		colIndex:   colIndex,
		blockIndex: blockIndex,
		validity:   validityIndex,
	}

}

type Float64ColumnWriter struct {
	columnType  ColumnType
	bw          *io.BinaryWriter
	src         Float64ColumnSource
	encoder     encoding.Float64Encoder
	colIndex    index.Float64IndexWriter
	blockIndex  index.BlockIndexWriter
	validity    index.ValidityIndexWriter
	numOfValues int
	cardinality int

	blkEnd         int
	blkIdxEnd      int
	encoderEnd     int
	colIdxEnd      int
	validityIdxEnd int
}

func (w *Float64ColumnWriter) Write() {

	for w.src.HasNext() {

		values := w.src.Next()

		w.numOfValues += values.Len()

		w.encoder.Encode(values)

		if w.colIndex != nil {
			w.colIndex.Index(values)
		}

		if w.src.HasNulls() {
			w.validity.Index(values.Rid())
		}

	}

	w.encoder.FlushBlocks()

	w.blkEnd = w.bw.Offset()

	// some column types like boolean col don't write blocks.
	if w.blockIndex != nil {

		w.blockIndex.Flush()

		w.blkIdxEnd = w.bw.Offset()

	}

	w.encoder.Flush()

	w.encoderEnd = w.bw.Offset()

	// TODO(gvelo) if the column is not indexed estimate
	// cardinality anyways using datasketches.
	if w.colIndex != nil {

		w.colIndex.Flush()

		w.colIdxEnd = w.bw.Offset()

		w.cardinality = w.colIndex.Cardinality()

	}

	if w.src.HasNulls() {

		w.validity.Flush()

		w.validityIdxEnd = w.bw.Offset()

	}

	w.writeFooter()

}

func (w *Float64ColumnWriter) writeFooter() {

	entry := w.bw.Offset()

	w.bw.WriteUvarint(int(w.encoder.Type()))
	w.bw.WriteUvarint(w.blkEnd)
	w.bw.WriteUvarint(w.blkIdxEnd)
	w.bw.WriteUvarint(w.encoderEnd)
	w.bw.WriteUvarint(w.colIdxEnd)
	w.bw.WriteUvarint(w.validityIdxEnd)
	w.bw.WriteUvarint(w.numOfValues)
	w.bw.WriteUvarint(w.cardinality)

	w.bw.WriteFixedInt(entry)

}

func NewBoolColumnWriter(columnType ColumnType,
	src BoolColumnSource,
	encoder encoding.BoolEncoder,
	colIndex index.BoolIndexWriter,
	blockIndex index.BlockIndexWriter,
	validityIndex index.ValidityIndexWriter,
	bw *io.BinaryWriter) *BoolColumnWriter {

	return &BoolColumnWriter{
		columnType: columnType,
		src:        src,
		bw:         bw,
		encoder:    encoder,
		colIndex:   colIndex,
		blockIndex: blockIndex,
		validity:   validityIndex,
	}

}

type BoolColumnWriter struct {
	columnType  ColumnType
	bw          *io.BinaryWriter
	src         BoolColumnSource
	encoder     encoding.BoolEncoder
	colIndex    index.BoolIndexWriter
	blockIndex  index.BlockIndexWriter
	validity    index.ValidityIndexWriter
	numOfValues int
	cardinality int

	blkEnd         int
	blkIdxEnd      int
	encoderEnd     int
	colIdxEnd      int
	validityIdxEnd int
}

func (w *BoolColumnWriter) Write() {

	for w.src.HasNext() {

		values := w.src.Next()

		w.numOfValues += values.Len()

		w.encoder.Encode(values)

		if w.colIndex != nil {
			w.colIndex.Index(values)
		}

		if w.src.HasNulls() {
			w.validity.Index(values.Rid())
		}

	}

	w.encoder.FlushBlocks()

	w.blkEnd = w.bw.Offset()

	// some column types like boolean col don't write blocks.
	if w.blockIndex != nil {

		w.blockIndex.Flush()

		w.blkIdxEnd = w.bw.Offset()

	}

	w.encoder.Flush()

	w.encoderEnd = w.bw.Offset()

	// TODO(gvelo) if the column is not indexed estimate
	// cardinality anyways using datasketches.
	if w.colIndex != nil {

		w.colIndex.Flush()

		w.colIdxEnd = w.bw.Offset()

		w.cardinality = w.colIndex.Cardinality()

	}

	if w.src.HasNulls() {

		w.validity.Flush()

		w.validityIdxEnd = w.bw.Offset()

	}

	w.writeFooter()

}

func (w *BoolColumnWriter) writeFooter() {

	entry := w.bw.Offset()

	w.bw.WriteUvarint(int(w.encoder.Type()))
	w.bw.WriteUvarint(w.blkEnd)
	w.bw.WriteUvarint(w.blkIdxEnd)
	w.bw.WriteUvarint(w.encoderEnd)
	w.bw.WriteUvarint(w.colIdxEnd)
	w.bw.WriteUvarint(w.validityIdxEnd)
	w.bw.WriteUvarint(w.numOfValues)
	w.bw.WriteUvarint(w.cardinality)

	w.bw.WriteFixedInt(entry)

}

func NewByteSliceColumnWriter(columnType ColumnType,
	src ByteSliceColumnSource,
	encoder encoding.ByteSliceEncoder,
	colIndex index.ByteSliceIndexWriter,
	blockIndex index.BlockIndexWriter,
	validityIndex index.ValidityIndexWriter,
	bw *io.BinaryWriter) *ByteSliceColumnWriter {

	return &ByteSliceColumnWriter{
		columnType: columnType,
		src:        src,
		bw:         bw,
		encoder:    encoder,
		colIndex:   colIndex,
		blockIndex: blockIndex,
		validity:   validityIndex,
	}

}

type ByteSliceColumnWriter struct {
	columnType  ColumnType
	bw          *io.BinaryWriter
	src         ByteSliceColumnSource
	encoder     encoding.ByteSliceEncoder
	colIndex    index.ByteSliceIndexWriter
	blockIndex  index.BlockIndexWriter
	validity    index.ValidityIndexWriter
	numOfValues int
	cardinality int

	blkEnd         int
	blkIdxEnd      int
	encoderEnd     int
	colIdxEnd      int
	validityIdxEnd int
}

func (w *ByteSliceColumnWriter) Write() {

	for w.src.HasNext() {

		values := w.src.Next()

		w.numOfValues += values.Len()

		w.encoder.Encode(values)

		if w.colIndex != nil {
			w.colIndex.Index(values)
		}

		if w.src.HasNulls() {
			w.validity.Index(values.Rid())
		}

	}

	w.encoder.FlushBlocks()

	w.blkEnd = w.bw.Offset()

	// some column types like boolean col don't write blocks.
	if w.blockIndex != nil {

		w.blockIndex.Flush()

		w.blkIdxEnd = w.bw.Offset()

	}

	w.encoder.Flush()

	w.encoderEnd = w.bw.Offset()

	// TODO(gvelo) if the column is not indexed estimate
	// cardinality anyways using datasketches.
	if w.colIndex != nil {

		w.colIndex.Flush()

		w.colIdxEnd = w.bw.Offset()

		w.cardinality = w.colIndex.Cardinality()

	}

	if w.src.HasNulls() {

		w.validity.Flush()

		w.validityIdxEnd = w.bw.Offset()

	}

	w.writeFooter()

}

func (w *ByteSliceColumnWriter) writeFooter() {

	entry := w.bw.Offset()

	w.bw.WriteUvarint(int(w.encoder.Type()))
	w.bw.WriteUvarint(w.blkEnd)
	w.bw.WriteUvarint(w.blkIdxEnd)
	w.bw.WriteUvarint(w.encoderEnd)
	w.bw.WriteUvarint(w.colIdxEnd)
	w.bw.WriteUvarint(w.validityIdxEnd)
	w.bw.WriteUvarint(w.numOfValues)
	w.bw.WriteUvarint(w.cardinality)

	w.bw.WriteFixedInt(entry)

}
